### ISSUE TITLE
In Executor class method listerProviders(...) needs to set the terminology provider to the context

### ISSUE THREAD

**Issue by tsaferb** [DBCG/cql_execution_service#1]
context.registerTerminologyProvider(terminologyProvider);

**Comment by c-schuler** [comment]
Is this resulting in an error? If so, then please share the error. The terminology provider is set in the data provider, which is registered with the context.

**Comment by tsaferb** [comment]
// CQL expression that references a value set
valueset "Female Administrative Sex": '2.16.840.1.113883.3.560.100.2'
define InDemographic:
  Patient.gender in "Female Administrative Sex"
you get
java.lang.NullPointerException
	at org.opencds.cqf.cql.elm.execution.InValueSetEvaluator.inValueSet(InValueSetEvaluator.java:69)
	at org.opencds.cqf.cql.elm.execution.InValueSetEvaluator.evaluate(InValueSetEvaluator.java:109)

because provider is null
provider = context.resolveTerminologyProvider(); returns null

But if I set the terminology to the context like 
context.registerTerminologyProvider(terminologyProvider);
it properly returns the terminology and calls the terminology server.
