### ISSUE TITLE
CQF Ruler Output Question

### ISSUE THREAD

**Issue by karenhansen-rojas** [DBCG/cql_execution_service#30]
Is there any documentation for outputs that CQF Ruler will generate in the event of a failure/error occurring during the $evaluate-measure operation? If not, what do those responses look like?

This information will help when Link needs to create Notification and Audit events when CQFRuler encounters a failure while creating a MeasureReport.

**Comment by kjcormier** [comment]
Like all FHIR operations, $evaluate-measure will generate an OperationOutcome given a server failure (500 HTTP code). Additionally, most other 400 codes will generate an OperationOutcome. The details of the failure (such as a stacktrace, particulars about a missing resource and so on) will be in the "issues" list of the OperationOutcome.
