### ISSUE TITLE
Passing in Parameters

### ISSUE THREAD

**Issue by jduke99** [DBCG/cql_execution_service#7]
Sorry if this is a simple question, but how do I pass in parameters (eg Measurement Period) to the CQL engine (/cql/evaluate)?

eg, I have a parameter in my CQL like:

parameter "MyString" String

and I want to pass in this string when I execute the CQL.

Thanks!

**Comment by brynrhodes** [comment]
Hi @jduke99 , we have not exposed the ability to pass parameters through the service yet, but it would be a pretty straight-forward extension. We'll add it to the list to expose on the service here.

**Comment by c-schuler** [comment]
This has been addressed.
